### ISSUE TITLE
requires root privileges

### ISSUE THREAD

**Issue by setop** [anordal/selfdock#5]
The README states :

> [selfdock] Doesn't give or require root

But install script requires sudo and does : 

https://github.com/anordal/selfdock/blob/8dafd07f30b1a4336f529fc5325d27d83766fdbc/install.mk#L29

The fact is, after compilation, if executed under unprivileged user, we get :

> No suid. Please check that the program is installed correctly.

And with suid set for current user, we get :

> clone: Operation not permitted

It looks like [podman](https://podman.io/) manage to run containers without root suid.

```
$ ll $(which podman)
.rwxr-xr-x 1 36M root  4 Aug  2021 /usr/bin/podman
```

**Comment by anordal** [comment]
Yes, it's a suid-root program.

That's an implementation detail, not a contradiction: It drops back to the invoking user before running anything. So you can't use it to run anything as root. That's the deal.

This is because Linux namespaces requires it. Interesting that podman seems to do without. I would guess it just uses capabilities instead. I simply haven't researched which specific capabilities I would need. Capabilities would still require root to install, though.

If you think this is a bug, it's closed; if it's a feature request for something I don't know about yet, I'm open for that.

**Comment by setop** [comment]
Hi
Thanks for the quick reply.
Since it is mainly a lack of knowledge from my side, I agree with the closing.
I gonna study the source code then.
Cheers
